dataset:
  train:
    name: diode
    prob_ls: [0.9, 0.1]
    disp_name: diode_train
    dir: train.tar
    filenames: data_split/diode/diode_train_all_filename_list.txt
    resize_to_hw:
    - 480
    - 640